# Postgresql
spring:
  datasource:
    url: jdbc:postgresql://132.145.83.126:5432/plog_dev
    username: plog
    password: 565plog9632@

# JPA
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
      format_sql: true
    show-sql: true

logging:
  level:
    root: debug