spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

cloud:
  aws:
    s3:
      bucket: test-bucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: TEST_AWS_ACCESS_KEY
      secretKey: TEST_AWS_SECRET_KEY