# Postgresql
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl_auto: none
        format_sql: true
        show_sql: true

# springfox
springfox:
  documentation:
    swagger:
      use-model-v3: false

#logging:
#  level:
#    root: debug


---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: dev
