# Postgresql
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl_auto: none
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: plogcareers@gmail.com
    password: ppvuczvpltvulxex

    properties:
      mail:
        smtp:
          ssl:
            protocols: TLSv1.2
          auth: true
          starttls:
            enable: true
            required: true
# springfox
springfox:
  documentation:
    swagger:
      use-model-v3: false

#logging:
#  level:
#    root: debug


---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: dev
