# Postgresql
spring:
  datasource:
    url: jdbc:postgresql://db.plogcareers.com:5432/plog_dev
    username: plog
    password: 565plog9632@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# JPA
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: none
      format_sql: true
    show-sql: true

#logging:
#  level:
#    root: debug
