std-errors:
  errors:
    # ums domain
    LOGIN_EMAIL_PW_UNMATCHED:
      code: 1001
      message: "이메일이나 비밀번호가 일치하지 않습니다."
    EMAIL_ALREADY_EXIST:
      code: 1002
      message: "해당 이메일이 이미 존재합니다."
    JOIN_FAILED:
      code: 1003
      message: "회원가입에 실패하였습니다."
    USER_NOT_FOUND:
      code: 1004
      message: "정보가 일치하는 유저가 없습니다."

    # blog domain
    POSTING_NOT_FOUND:
      code: 2001
      message: "게시물이 존재하지 않습니다."
    TAG_NOT_FOUND:
      code: 2002
      message: "태그가 존재하지 않습니다."

    # Common
    INTERNAL_SERVER_ERROR:
      code: 9999
      message: "알 수 없는 에러입니다."