name: Measure coverage

on:
  pull_request:
    branches: [ main, feat/*, fix/*, test/* ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Run Coverage
        run: |
          chmod +x gradlew    
          ./gradlew test
          ./gradlew jacocoTestReport
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GH_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0