name: Measure coverage

on:
  pull_request:
    branches: [ main, feat/*, fix/*, test/* ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Run Test
        run: |
          chmod +x gradlew    
          ./gradlew test
          ./gradlew jacocoTestReport

      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          name: Maven Tests
          path: build/test-results/**/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
